### ISSUE TITLE
PersistentBeanFactory::createValueFromPersistentBean can't handle Arrays

### ISSUE THREAD

**Issue by skrilagg** [ppi-ag/deep-sampler#60]
Hi,

when loading Data that contains an array as a response an InstantiationException is thrown.
One workaround might be creating an extension for that, but this might be core functionality the factory should provide.

Instead of a stracktrace, a simple Unit Test to clarify:

```
@Test
@DisplayName("createValueFromPersistentBean can handle Arrays")
void createValueFromPersistentBean() {
    PersistentBeanFactory factory = new PersistentBeanFactory();
    
    PersistentBean bean = new DefaultPersistentBean();
    bean.setValues(Collections.emptyMap());
    
    Assertions.assertDoesNotThrow(() -> factory.createValueFromPersistentBean(bean, IOneInterface[].class));
}

interface IOneInterface {
    
    void sampleMethod();
}
```

best regards,
Michel Pittelkow

**Comment by rcschrg** [comment]
Hi,

thanks for your bug report! In the linked pull request I implemented the support for serializing and deserializing object arrays with the persistence model, **but** I fear that won't satisfy your test completly. 

The problem is part of the design, we are creating persistent beans of objects or jsons to get rid of the type informations, as we are only matching by structure. That means when deserializing we do not know the real type of the object anymore, all we have is the structure of the output bean, defined by the sample defintion. As a result its not possible to use interface arrays (or interfaces at all) as declared types with the persistence. 

So do you need to declare interface types, too? Its surely possible to make that work, but it will go along with the disadvantage, that these serialized beans would have to contain type informations, what would decrease the maintainability. If you need such a feature, please create another issue.

Greetings
Rico Schrage
